#!/usr/bin/env python3
from subprocess import run
from glob import glob
import os.path as op

print(op.abspath(__file__))
scripts = glob(op.join(op.dirname(op.abspath(__file__)), '..', 'examples', '*.py'))
print('Running the following scripts: {}'.format(scripts))
for iscript in scripts:
    # Run each script, this will ensure data is downloaded in the built image and that the scripts work.
    call = ['python', iscript]
    print('Running script: {}'.format(iscript))
    run(call, check=True)